# Primer playbook en YAML

# Esta esrtablecido en el inventario
- hosts: test1
  tasks:
    - debug:
        var: MSG

    - debug:
        msg: "Yo no me voy a ejecutar"
      tags: no-exec

    - debug:
        msg: "YO si me voy a ejecutar :)"
      tags: si-exec
    # - shell: echo $MSG  y Jenkins > /tmp/hola-ansible
